### PR TITLE
Include <memory> where std::unique_ptr is used

### PR DESCRIPTION
**Pull request by musicinmybrain**
Include the `memory` header where `std::unique_ptr` is used.

This is far from a full implementation of the “include what you use” concept, and indeed the [tool of that name](https://include-what-you-use.org/) could be helpful, but it does fix a concrete failure to compile on GCC 12.0.1, in which an implicit recursive include via another header was no longer present.

```
/builddir/build/BUILD/giada-0.20.0/src/utils/string.cpp: In function 'std::string giada::u::string::format(const char*, ...)':
/builddir/build/BUILD/giada-0.20.0/src/utils/string.cpp:87:14: error: 'unique_ptr' is not a member of 'std'
   87 |         std::unique_ptr<char[]> tmp(new char[size]);
      |              ^~~~~~~~~~
/builddir/build/BUILD/giada-0.20.0/src/utils/string.cpp:34:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
   33 | #include <iomanip>
  +++ |+#include <memory>
   34 | 
/builddir/build/BUILD/giada-0.20.0/src/utils/string.cpp:87:25: error: expected primary-expression before 'char'
   87 |         std::unique_ptr<char[]> tmp(new char[size]);
      |                         ^~~~
/builddir/build/BUILD/giada-0.20.0/src/utils/string.cpp:92:18: error: 'tmp' was not declared in this scope; did you mean 'tm'?
   92 |         vsprintf(tmp.get(), format, args);
      |                  ^~~
      |                  tm
```

### CODE REVIEW

**Comment by gvnnz** [comment]
Thank you @musicinmybrain !
