### ISSUE TITLE
Build failure on macOS 15.0 arm64

### ISSUE THREAD

**Issue by rnkn** [monocasual/giada#704]
**Environment**
- OS: macOS 15.0
- Giada version: 1.0.0

**Describe the bug**
A build failure with the following error when linking `giada`:

```
[100%] Linking CXX executable giada
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SCContentFilter", referenced from:
       in libfltk.a[174](Fl_cocoa.mm.o)
  "_OBJC_CLASS_$_SCScreenshotManager", referenced from:
       in libfltk.a[174](Fl_cocoa.mm.o)
  "_OBJC_CLASS_$_SCShareableContent", referenced from:
       in libfltk.a[174](Fl_cocoa.mm.o)
  "_OBJC_CLASS_$_SCStreamConfiguration", referenced from:
       in libfltk.a[174](Fl_cocoa.mm.o)
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/giada.dir/build.make:3590: giada] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:176: CMakeFiles/giada.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**To Reproduce**

```
$ git clone --depth 1 https://github.com/monocasual/giada.git
$ cd giada
$ git submodule update --init --recursive --depth 1
$ git -C src/deps/juce/ reset --hard origin/master
$ git -C src/deps/fltk/ reset --hard origin/master
$ sed -i~ 's/LANGUAGES CXX/LANGUAGES C CXX/' CMakeLists.txt
$ cmake -S . -B build
$ cmake --build build/
```

**Expected behavior**
Successful build.

**Additional context**
The JUCE and FLTK submodules needed to be updated to master to build on macOS 15.0. Without adding C to the project LANGUAGES, CMake would fail.
